### PR TITLE
Update icon

### PR DESCRIPTION
**Pull request by khronokernel**

### CODE REVIEW

**Comment by vit9696** [comment]
Can you actually open this icon? Preview produces an error when I try to open this file.

**Comment by khronokernel** [comment]
@vit9696 Preview doesn't open the image but once added into the resources of the App it will display correctly. Preview doesn't seem to work with .icns in general, at least from what I've seen

**Comment by vit9696** [comment]
I think Preview may not support all the legacy ICNS chunks from early days, but other than that it works just fine for me with other images. I am afraid this exact icns is just malformed.

**Comment by khronokernel** [comment]
Try this one: [khronokernel/ProperTree](https://github.com/khronokernel/ProperTree)
Just remade the icon again

**Comment by vit9696** [comment]
This time it worked, but I believe you are best to create all the sizes for best looks. Try this script maybe? https://stackoverflow.com/a/20703594

**Comment by khronokernel** [comment]
Thank you, just pushed a [new PR](https://github.com/corpnewt/ProperTree/pull/24) with the changes

**Pull request merged**
