### PR TITLE
Added cross-platform binary builds and Travis CI support

### PR DESCRIPTION
**Pull request by Dids**
Uses `pyinstaller` to build a single-file executable for Linux, macOS and Windows, thanks to Travis CI.

To enable Travis, you just need to go [here](https://travis-ci.org), login with your GitHub account, go to Settings, search for `ProperTree` and toggle the on/off switch next to it. After that, each commit should trigger a build.

You can see a successful sample build output here: https://travis-ci.org/Dids/ProperTree/builds/529411076

Note that this doesn't have any tag/release logic yet, but I can work on that next if you're interested. :)

EDIT: Sorry, missed PR #2, although it has a bit of a different approach.

### CODE REVIEW

**Comment by dhinakg** [comment]
[Travis-CI.org](travis-ci.org) is deprecated, use [Travis-CI.com](travis-ci.com) instead.

**Comment by Dids** [comment]
> [Travis-CI.org](http://travis-ci.org) is deprecated, use [Travis-CI.com](http://travis-ci.com) instead.

Source? Couldn't find anything solid on Google, and last I checked travis-ci.com was for paid/commercial projects, while travis-ci.org was for free/public/OSS. I have hundreds of projects building there, and don't see any deprecation notices, nor have I received any such emails from them.

**Comment by dhinakg** [comment]
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
image
They've said that migration to .com will occur soon™, but after a year it still hasn't happened

**Comment by cclauss** [comment]
Please fix git conflicts.

**Pull request merged**
