### PR TITLE
macOS Dark Mode support

### PR DESCRIPTION
**Pull request by cktse**
Replace hardcoded background colors with macOS named colors from ttk, which will change according to light/dark mode

### CODE REVIEW

**Comment by kittywhiskers** [comment]
Not able to reproduce changes on macOS Catalina 10.15.5 w/ Dark Mode, could you send some screenshots?

**Comment by cktse** [comment]
> Not able to reproduce changes on macOS Catalina 10.15.5 w/ Dark Mode, could you send some screenshots?

See below. I suspect it could be the version of tkinter you are running. Dark Mode support was added only fairly recently since 8.6.10. I am using MacPorts for my python. Apologies if this does not work for you.

#
DarkMode
LightMode

**Comment by kittywhiskers** [comment]
Weird, my setup might be broken, I'll cherry-pick the commits and give it a shot. Thanks for your work 😊

**Comment by cktse** [comment]
In case if you are using MacPort for your python install as well, you need to install the +quartz variant of tk: port uninstall tk; port install tk +quartz

**Pull request merged**
